### ISSUE TITLE
Chrome Manifest V3 Content Security Policy error with inline script

### ISSUE THREAD

**Issue by deastr** [arikw/extension-page-context#2]
Hi. I'm developing an extension using extension-page-context. It works fine for MV2 on Chrome but when I tried MV3 I started to get this error:

```
Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 
'wasm-unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-6FL5DgIT2dKyLLIqLeHLa1UbUhKKfn8S1tDViW68mA4='), 
or a nonce ('nonce-...') is required to enable inline execution.

// run the script
doc.documentElement.appendChild(scriptElm);
```

The extension I'm developing will work on https://www.twitch.tv/. I've checked response headers and there aren't any CSP headers as far as I can see.

It works fine on Firefox with MV3.

Edit: I think I need to add content_security_policy to manifest.json to allow this, I'll investigate and report back.

**Comment by deastr** [comment]
Chrome MV3 doesn't accept 'unsafe-inline' in content_security_policy. I think this type of injecting doesn't work anyomre in MV3, I think it needs to be changed into scriptElm.src = <file.js>.

**Comment by deastr** [comment]
I converted injected scripts into a seperate file and injected it using `script.src`, this seems to be working on Chrome with MV3:

```
var scriptTag = document.createElement('script');
scriptTag.src = chrome.runtime.getURL('content-inline.js');
document.documentElement.appendChild(scriptTag);
```

Need to add js file to manifest.json like this:

```
"web_accessible_resources": [
	  {
		  "resources": [ "content-inline.js" ],
		  "matches": [  ...  ]
		}
	]
```

I'm leaving the issue open for it to be seen, feel free to close.

**Comment by arikw** [comment]
Thank you very much @deastr for sharing the solution.
Is it backward compatible with MV2?
A contribution of a pull request would be of great help to me

**Comment by deastr** [comment]
It is backward compatible with MV2.

I'm not available to create PR right now but you can see it here, it's the same one I've posted before:

https://github.com/deastr/TwitchPerChannelAudio/blob/main/src/content.js#L2

**Comment by arikw** [comment]
I don't see where you're using [`runInPageContext()`](https://github.com/arikw/extension-page-context/blob/master/page-context.js#L12), so I'm not sure what's to be fixed.
Can you please explain?

**Comment by deastr** [comment]
I don't use runInPageContext anymore, since I've discovered injecting external JS file is all I needed. Sorry if it wasn't clear.
